name: mlb-pitch-prediction
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - xgboost
  - seaborn
  - matplotlib
  - imbalanced-learn
  - jupyter
  -make
  - pytest
  - tensorflow
  - pip
  - pip:
      - nbconvert
      - pybaseball
      - PyGithub
      - PyJWT
      - cryptography
